### ISSUE TITLE
Incompatible with useGesture’s useWheel event handler

### ISSUE THREAD

**Issue by wolfgangschoeffel** [snelsi/lethargy-ts#5]
**Describe the bug**
When passing the event from useGesture’s wheel gesture, I get this error:

Uncaught Error: No event provided

**To Reproduce**
Implement basic wheel gesture like in this example: 
https://codesandbox.io/p/sandbox/lethargy-2coe8?file=%2Fsrc%2Findex.js%3A22%2C41

**Expected behavior**
lethargy.check(event) is expected to return -1 or 1 but instead the above mentioned error is thrown.

**Screenshots**
![Screenshot 2024-01-03 at 20 18 06](https://github.com/snelsi/lethargy-ts/assets/1621535/0b793cad-cc50-43dd-871f-97644d65336b)

**Comment by snelsi** [comment]
`Lethargy.check` function expects you to pass an instance of `Event` to it. 
Otherwise it will throw an error.

Looks like `@use-gesture` library you're using returns an instance of `SyntheticEvent`, which is a custom React wrapper for native Events. That's why you're seeing this error message.

I'll add a check for this use-case in the next release, but for now you quickly fix this on your side by passing `event.nativeEvent` like this:

```diff
const bind = useWheel(({ event }) => {
-  const isHuman = lethargy.check(event)
+  const isHuman = lethargy.check(event.nativeEvent)
```

**Comment by wolfgangschoeffel** [comment]
Thank you!
